apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  HEADER_NAME: "Ade"
  S3_BUCKET: "clo835-project-bucket01"
  S3_KEY: "images/background1.jpg"
  AWS_REGION: "us-east-1"
  DBHOST: "mysql"
  DBPORT: "3306"
  DATABASE: "employees"